services:
  - type: web
    name: calculator
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y default-libmysqlclient-dev build-essential
      pip install -r requirements.txt
    startCommand: gunicorn calculator.wsgi:application
